### ISSUE TITLE
Index Error: list index out of range

### ISSUE THREAD

**Issue by user133337** [petyasoft/yescoin#2]
![image](https://github.com/petyasoft/yescoin/assets/168750691/e017e7d1-ff34-4aea-9b99-4cf14f197deb)
how to fix it?

**Comment by petyasoft** [comment]
you have the correct proxy format?
correct format ip:port:login:password

**Comment by petyasoft** [comment]
> ![image](https://private-user-images.githubusercontent.com/168750691/327565358-e017e7d1-ff34-4aea-9b99-4cf14f197deb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2ODU3MTIsIm5iZiI6MTcxNDY4NTQxMiwicGF0aCI6Ii8xNjg3NTA2OTEvMzI3NTY1MzU4LWUwMTdlN2QxLWZmMzQtNGFlYS05Yjk5LTRjZjE0ZjE5N2RlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQyMTMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGE4NTg4ZWY0MjQ5M2U2NjJiNGY0NDFhOTgwNzFiNzU4YzAzMGI1NjRlMWU0ZGE3MDNkMjUxNDlkMjMxMzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P9-0Iv65bCqX4dYaSoBryAIln0TwsnX3_tZNaeyDI08) how to fix it?



> ![image](https://private-user-images.githubusercontent.com/168750691/327565358-e017e7d1-ff34-4aea-9b99-4cf14f197deb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2ODU3MTIsIm5iZiI6MTcxNDY4NTQxMiwicGF0aCI6Ii8xNjg3NTA2OTEvMzI3NTY1MzU4LWUwMTdlN2QxLWZmMzQtNGFlYS05Yjk5LTRjZjE0ZjE5N2RlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQyMTMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGE4NTg4ZWY0MjQ5M2U2NjJiNGY0NDFhOTgwNzFiNzU4YzAzMGI1NjRlMWU0ZGE3MDNkMjUxNDlkMjMxMzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P9-0Iv65bCqX4dYaSoBryAIln0TwsnX3_tZNaeyDI08) how to fix it?

you have the correct proxy format?
correct format ip:port:login:password

**Comment by user133337** [comment]
thanks a lot, corrected.
