### ISSUE TITLE
Why didn't the agency succeed    

### ISSUE THREAD

**Issue by hardwin1014** [petyasoft/yescoin#8]
17:54:54.39 | INFO | Thread 2 | 无天 | Start! | PROXY : None 17:54:55.40 | INFO | Thread 1 | SB571 | Start! | PROXY : None

**Comment by petyasoft** [comment]
something was wrong in the proxy file

**Comment by hardwin1014** [comment]
> something was wrong in the proxy file

Can you tell me what the proxy format is? I play other games in the proxy format http://name:password@ip:port

**Comment by hardwin1014** [comment]
> something was wrong in the proxy file
Now I change to ip:port:login:password this format, still can not.
![image](https://github.com/user-attachments/assets/1d636ec5-217f-4c5e-964e-948b710f9358)

**Comment by hardwin1014** [comment]
If it is None, my local IP address will be used by default, resulting in multiple accounts using the same IP address. unnumbered

**Comment by hardwin1014** [comment]
> something was wrong in the proxy file

I saw the format with your other game robots. Thank you, Sir

**Comment by hardwin1014** [comment]
> something was wrong in the proxy file

**I added sessions' name after the proxy, but it still got an error. Agents are good**
![image](https://github.com/user-attachments/assets/f28b2c95-616b-4fef-a632-c8c1c8251c79)
